version: "3.8"
services:
  react-store:
    build: ./react-store
    container_name: react-store-cont
    port:
      - '3000:3000'
    volumes:
      - ./react-store:/app
      - ./app/node_modules
    stdin_open: true
    tty: true  